// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imgoszzhbkssppspjnkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZ29zenpoYmtzc3Bwc3BqbmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjc4NDUsImV4cCI6MjA2ODg0Mzg0NX0.uJ_FTcZlBvdHeesywtwSkC5HRLEtbONY6OvcE6ZjM9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});